### ISSUE TITLE
Error Mixed Date y Decimal JSON

### ISSUE THREAD

**Issue by dltoya** [aplazame/php-sdk#14]
Fatal error: Uncaught TypeError: Return value of Aplazame\Serializer\Decimal::jsonSerialize() must be an instance of Aplazame\Serializer\mixed, int returned in /home/***/public_html/includes/vendor/aplazame/aplazame-api-sdk/src/Serializer/Decimal.php:38 Stack trace: #0 [internal function]: Aplazame\Serializer\Decimal->jsonSerialize() #1 /home/***/public_html/includes/vendor/aplazame/aplazame-api-sdk/src/Api/ApiRequest.php(67): json_encode(Object(stdClass)) #2 /home/***/public_html/includes/vendor/aplazame/aplazame-api-sdk/src/Api/Client.php(163): Aplazame\Api\ApiRequest->__construct(false, 1, '5981ee7c3b3b691...', 'POST', 'https://api.apl...', Object(stdClass)) #3 /home/***/public_html/includes/vendor/aplazame/aplazame-api-sdk/src/Api/Client.php(125): Aplazame\Api\Client->request('POST', '/checkout', Object(stdClass)) #4 /home/***/public_html/includes/modules/payment/aplazamev3.php(57): Aplazame\Api\Client->post('/checkout', Object(stdClass)) #5 /home/***/public_html/includes/modules/payment/aplazamev3.php(449 in /home/***/public_html/includes/vendor/aplazame/aplazame-api-sdk/src/Serializer/Decimal.php on line 38

**Comment by dltoya** [comment]
Es necesario quitar el mixed para evitar el error en la serialización del JSON

**Comment by alexhernandezord** [comment]
Esto es debido a que estáis usando una versión de PHP anterior a la 8.1. Usad la versión [v0.3.5](https://github.com/aplazame/php-sdk/releases/tag/v0.3.5) del SDK.
