### ISSUE TITLE
PHP 7.3 and checkout creation

### ISSUE THREAD

**Issue by nathanrod** [aplazame/php-sdk#8]
SDK version: 0.2.2
PHP version: 7.3.6
Example used: https://github.com/aplazame/php-sdk/blob/master/examples/step1_checkout_create.php

Issues:

1- TypeError: Argument 2 passed to Aplazame\Api\Client::post() must be of the type array

The example use a object rather than an array expected. I was able to bypass the exception by removing the array casting in the post method( vendor/aplazame/aplazame-api-sdk/src/Api/Client.php:127 ).

2- $order->total_amount =  Aplazame\Serializer\Decimal::fromFloat($invoice->total);
$invoice->total is 290.40
Returns a validation error. I was able to bypass it byt setting the total_amont to 29040. I also did the same with the order article prices.

After those changes are made, the widget is displayed but with an issue with the total displaying 290,39.999999 instead of 290.40.

I was not able to fix the amount issue.

**Comment by Maks3w** [comment]
Hi @nathanrod 

Thank you for your feedback.

About 1. I've fixed it and released a new version (v0.3.0)
About 2. My guess is `$invoice->total` is a string like `290,40` with the comma instead of period for decimal separation, just check you are passing a float or set `29040` directly to `$order->total_amount`

Regards

**Comment by nathanrod** [comment]
About 2- I never use commas, this is an example of payload to reproduce the issue:

object(stdClass)[564]
  public 'toc' => boolean true
  public 'merchant' => 
    object(stdClass)[552]
      public 'notification_url' => string 'http://dev.whmcsmod.com/modules/gateways/callback/aplazame.php' (length=62)
      public 'cancel_url' => string 'viewinvoice.php?id=647' (length=22)
      public 'success_url' => string 'viewinvoice.php?id=647' (length=22)
      public 'checkout_url' => string 'viewinvoice.php?id=647' (length=22)
  public 'order' => 
    object(stdClass)[538]
      public 'id' => string '647-1567082761' (length=14)
      public 'currency' => string 'EUR' (length=3)
      public 'tax_rate' => float 2100
      public 'total_amount' => float 29040
      public 'discount' => int 0
      public 'cart_discount' => int 0
      public 'articles' => 
        array (size=1)
          0 => 
            object(stdClass)[556]
              public 'id' => int 888
              public 'name' => string 'prueba factura' (length=14)
              public 'url' => string '' (length=0)
              public 'image_url' => string '' (length=0)
              public 'quantity' => int 1
              public 'price' => float 24000
  public 'customer' => 
    object(stdClass)[559]
      public 'email' => string '2301@whmcsmod.com' (length=17)
  public 'shipping' => 
    object(stdClass)[568]
      public 'first_name' => string 'Nathan' (length=6)
      public 'last_name' => string 'test' (length=4)
      public 'street' => string 'Rådhuspladsen 45' (length=17)
      public 'city' => string 'Yomomma' (length=7)
      public 'state' => string 'Yomomma' (length=7)
      public 'country' => string 'DK' (length=2)
      public 'postcode' => string '1456' (length=4)
      public 'name' => string 'Standard' (length=8)
      public 'price' => int 0

Seems to only happen with some amounts, not all so test it with 29040.

**Comment by nathanrod** [comment]
Found the issue, if i try to convert 29040  from float to int i get a 29039 due to a precision bug and your backend goes crazy.

https://stackoverflow.com/questions/3385685/php-unexpected-result-of-float-to-int-type-cast

https://www.php.net/manual/en/language.types.float.php

I guess you can close the issue?

**Comment by Maks3w** [comment]
I'm glad you find the problem. We were also worried about this.
